# This workflow generates a couple of artifacts that we use for testing

name: artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate test artifact alpha
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: artifact_alpha
        path: 'model/src/main/resources/artifact_alpha'
    - name: Generate test artifact beta
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: artifact_beta
        path: 'model/src/main/resources/artifact_beta'
