# This workflow generates a couple of artifacts that we use for testing

name: artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate test artifact alpha
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
      with:
        name: artifact_alpha
        path: 'model/src/main/resources/artifact_alpha'
    - name: Generate test artifact beta
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
      with:
        name: artifact_beta
        path: 'model/src/main/resources/artifact_beta'
