# Manually triggered, this workflow runs the integration tests that hit the github API endpoints

name: integration testing

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        BOWLBY_GH_AUTH_TOKEN: ${{ secrets.GH_API_AUTH_TOKEN }}
      run: mvn -B verify --file pom.xml -pl test -am -Dmctf.report.dir=latest

    - name: Save flow execution reports
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      id: artifact-upload-step
      if: success() || failure()
      with:
        name: flow_execution_reports
        path: |
          test/target/mctf/e2e/latest
          test/target/mctf/github/latest

    - name: Emit artifact links
      run: |
        echo " * [github isolation testing](http://132.226.129.14:56567/artifacts/therealryan/bowlby/${{ steps.artifact-upload-step.outputs.artifact-id }}/github/latest/index.html)" >> $GITHUB_STEP_SUMMARY
        echo " * [integration testing](http://132.226.129.14:56567/artifacts/therealryan/bowlby/${{ steps.artifact-upload-step.outputs.artifact-id }}/e2e/latest/index.html)" >> $GITHUB_STEP_SUMMARY
